compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
    npmAuthToken: "${IRT_GIT_TOKEN:-}"

npmScopes:
  inmanta:
    npmAlwaysAuth: true
    npmAuthToken: "${CLOUDSMITH_TOKEN:-I64G5nKb4S3jAuws}"
    npmRegistryServer: "https://npm.cloudsmith.io/inmanta/frontend-composer/"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
