yarnPath: .yarn/releases/yarn-3.5.0.cjs
nodeLinker: "node-modules"
npmAuthToken: "8351048aea466f498c6956e80275f58020fd5541"
npmScopes: ${GITHUB:-}
  inmanta:
    npmAlwaysAuth: true
    npmAuthToken: ${CLOUDSMITH_TOKEN:-}
    npmRegistryServer: "https://npm.cloudsmith.io/inmanta/frontend-composer/"
