yarnPath: .yarn/releases/yarn-3.5.0.cjs
nodeLinker: "node-modules"
npmAuthToken: ${GITHUB_TOKEN:-}
npmScopes:
  inmanta:
    npmAlwaysAuth: true
    npmAuthToken: ${CLOUDSMITH_TOKEN:-}
    npmRegistryServer: "https://npm.cloudsmith.io/inmanta/frontend-composer/"
