compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
    npmAuthToken: "${IRT_GIT_TOKEN:-}"

npmScopes:
  joint:
    npmAlwaysAuth: true
    npmAuthToken: "${JOINTJS_NPM_TOKEN}"
    npmRegistryServer: "https://npm.jointjs.com"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
