yarnPath: .yarn/releases/yarn-3.5.0.cjs
nodeLinker: "node-modules"
npmScopes:
  inmanta:
    npmAlwaysAuth: true
    npmAuthToken: ${YARN_NPM_AUTH_TOKEN:-}
    npmRegistryServer: "https://npm.cloudsmith.io/inmanta/frontend-composer/"
