yarnPath: .yarn/releases/yarn-3.5.0.cjs
nodeLinker: "node-modules"
npmRegistryServer: https://npm.pkg.github.com
npmAuthToken: ${IRT_GIT_TOKEN:-}
npmAlwaysAuth: true
npmScopes:
  inmanta:
    npmAlwaysAuth: true
    npmAuthToken: ${CLOUDSMITH_TOKEN:-}
    npmRegistryServer: "https://npm.cloudsmith.io/inmanta/frontend-composer/"
