nodeLinker: node-modules

npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
    npmAuthToken: "${IRT_GIT_TOKEN:-}"

npmScopes:
  inmanta:
    npmAlwaysAuth: true
    npmAuthToken: "${CLOUDSMITH_TOKEN:-}"
    npmRegistryServer: "https://npm.cloudsmith.io/inmanta/frontend-composer/"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
