description: Add configuration tab to settings page to allow updating environment settings
issue-nr: 1483
change-type: minor
destination-branches: [master, iso4]
sections:
  feature: "{{description}}"
