description: "Composer will highlight loose embedded entities on canvas and block ability to deploy until they are connected or removed"
issue-nr: 5366
change-type: patch
destination-branches:
  - master
  - iso7
sections:
  minor-improvement: "{{description}}"
