description: "Change information in the Form Modal to be more adequate when no instance is chosen, Make expand/collapse button action area bigger."
issue-nr: 5691
change-type: patch
destination-branches: [master, iso7]
sections:
  minor-improvement: "{{description}}"
