export const testInstance = {
  id: "b695e24c-67af-4177-9d82-12ea77bf9f33",
  environment: "8404deea-3621-4bca-9076-6a612115f810",
  service_entity: "carrierEthernetEvc",
  version: 4,
  config: {},
  state: "up",
  candidate_attributes: null,
  active_attributes: {
    allocated: {
      service_id: 10001,
      "evcEndPoints[identifier=demo-evc-002-ep-1].uni": {
        id: "inmanta:123-852-456",
        es_id: null,
        ports: [
          {
            id: "8",
            name: "1/1/c3/1",
            network_element: {
              id: "4",
              name: "router-west",
              device: {
                os: "TiMos",
                model: "7750 SR",
                vendor: "Nokia",
                mgmt_ip: "192.168.2.39",
                version: "20.10",
                mgmt_port: 24830,
                password_env: "NETCONF_DEVICE_PASSWORD",
                username_env: "NETCONF_DEVICE_USER",
              },
              router_ip: "10.255.255.4",
            },
          },
        ],
        lag_id: null,
        es_name: null,
      },
      "evcEndPoints[identifier=demo-evc-002-ep-2].uni": {
        id: "inmanta:456-852-789",
        es_id: null,
        ports: [
          {
            id: "3",
            name: "1/1/c2/1",
            network_element: {
              id: "2",
              name: "router-east",
              device: {
                os: "TiMos",
                model: "7750 SR",
                vendor: "Nokia",
                mgmt_ip: "192.168.2.39",
                version: "20.10",
                mgmt_port: 22830,
                password_env: "NETCONF_DEVICE_PASSWORD",
                username_env: "NETCONF_DEVICE_USER",
              },
              router_ip: "10.255.255.2",
            },
          },
        ],
        lag_id: null,
        es_name: null,
      },
    },
    identifier: "demo-evc-002",
    service_id: 10001,
    evcEndPoints: [
      {
        identifier: "demo-evc-002-ep-1",
        evcEndPointMap: {
          type: "LIST",
          vlanIdList: [
            {
              vlanId: 602,
            },
          ],
        },
        carrierEthernetSubscriberUni: {
          href: "inmanta:123-852-456",
        },
        egressBandwidthProfilePerEndPoint: [
          {
            cir: 1000000,
          },
          {
            cir: 2000000,
          },
        ],
      },
      {
        identifier: "demo-evc-002-ep-2",
        evcEndPointMap: {
          type: "LIST",
          vlanIdList: [
            {
              vlanId: 603,
            },
          ],
        },
        carrierEthernetSubscriberUni: {
          href: "inmanta:456-852-789",
        },
        egressBandwidthProfilePerEndPoint: [
          {
            cir: 1000000,
          },
          {
            cir: 2000000,
          },
        ],
      },
    ],
    connectionType: "POINT_TO_POINT",
    ext_networkBackend: {
      type: "EVPN",
    },
  },
  rollback_attributes: null,
  created_at: "2023-04-16T12:22:46.856481",
  last_updated: "2023-04-16T12:23:25.041340",
  callback: [],
  deleted: false,
  deployment_progress: {
    total: 4,
    failed: 0,
    deployed: 4,
    waiting: 0,
  },
  service_identity_attribute_value: "demo-evc-002",
};

export const testService = {
  attributes: [
    {
      name: "allocated",
      description:
        "A dictionary holding all the allocated values of the service",
      modifier: "r",
      type: "dict?",
      default_value: null,
      default_value_set: true,
      validation_type: null,
      validation_parameters: null,
    },
    {
      name: "connectionType",
      description: "",
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: "enum",
      validation_parameters: {
        names: {
          MULTIPOINT: "MULTIPOINT",
          POINT_TO_POINT: "POINT_TO_POINT",
        },
        value: "connection_type",
      },
    },
    {
      name: "identifier",
      description:
        "Used to identify an EVC within the SP Network. Reference MEF 10.4\nSection 8.1 EVC ID Service Attribute.",
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: null,
      validation_parameters: null,
    },
    {
      name: "service_id",
      description: null,
      modifier: "r",
      type: "int?",
      default_value: null,
      default_value_set: true,
      validation_type: "pydantic.PositiveInt?",
      validation_parameters: null,
    },
  ],
  embedded_entities: [
    {
      name: "evcEndPoints",
      description:
        "An EvcEndPoint is a construct at a UNI that selects a subset of the Service Frames\n\nthat pass over the UNI.An EvcEndPoint represents the logical attachment of an Evc\nto a UNI. Reference MEF 10.4 Section 10 EVC EP Service Attributes.",
      modifier: "rw+",
      lower_limit: 2,
      upper_limit: null,
      attributes: [
        {
          name: "identifier",
          description:
            "A string that is used to allow the Subscriber and Service Provider\nto uniquely identify the EvcEndPoint for operations purposes.\nReference MEF 10.4 Section 10.1 EVC EP ID Service Attribute.",
          modifier: "rw",
          type: "string",
          default_value: null,
          default_value_set: false,
          validation_type: null,
          validation_parameters: null,
        },
      ],
      embedded_entities: [
        {
          name: "egressBandwidthProfilePerEndPoint",
          description:
            "Bandwidth Profile for egress interfaces that support the tuple set of cir,\n\ncirMax, rank and envelope.",
          modifier: "rw+",
          lower_limit: 0,
          upper_limit: null,
          attributes: [
            {
              name: "cir",
              description:
                "Attribute represents Committed Information Rate. When added to\nunused committed bandwidth provided from higher-ranked\nBandwidth Profile Flows (depending on the value of CF for the\nhigher-ranked Bandwidth Profile Flows), limits the average rate\nin bits per second at which Service Frames for this Bandwidth Profile\nFlow can be declared Green.",
              modifier: "rw+",
              type: "int",
              default_value: null,
              default_value_set: false,
              validation_type: "pydantic.PositiveInt",
              validation_parameters: null,
            },
          ],
          embedded_entities: [],
          inter_service_relations: [],
          key_attributes: [],
        },
        {
          name: "evcEndPointMap",
          description:
            "VLAN ID types, ALL for all VLAN IDs, LIST for a list of VLAN IDs, EXCEPT\n\nfor all VLAN IDs except the listed, UNTAGGED to indicate that untagged\nand priority-tagged frames are mapped to this end point. Reference MEF 10.4\nSection 10.4 EVC EP Map Service Attribute.",
          modifier: "rw",
          lower_limit: 1,
          upper_limit: 1,
          attributes: [
            {
              name: "type",
              description: "",
              modifier: "rw",
              type: "string",
              default_value: null,
              default_value_set: false,
              validation_type: "enum",
              validation_parameters: {
                names: {
                  ALL: "ALL",
                  LIST: "LIST",
                },
                value: "vlan_id_list_type",
              },
            },
          ],
          embedded_entities: [
            {
              name: "vlanIdList",
              description:
                "Data type with single attribute, vlanId which is defined as a PostiveInteger.\n\nValue 1 to 4094. Ref-erence MEF 10.4 Section 10.4 EVC EP Map Service Attribute\nand MEF 26.2 Section 14.9 Opera-tor UNI Default CE-VLAN ID Service Attribute.",
              modifier: "rw",
              lower_limit: 0,
              upper_limit: null,
              attributes: [
                {
                  name: "vlanId",
                  description: "",
                  modifier: "rw",
                  type: "int",
                  default_value: null,
                  default_value_set: false,
                  validation_type: "pydantic.conint",
                  validation_parameters: {
                    ge: 1,
                    le: 4094,
                  },
                },
              ],
              embedded_entities: [],
              inter_service_relations: [],
              key_attributes: [],
            },
          ],
          inter_service_relations: [],
          key_attributes: [],
        },
        {
          name: "carrierEthernetSubscriberUni",
          description: null,
          modifier: "rw",
          lower_limit: 1,
          upper_limit: 1,
          attributes: [
            {
              name: "href",
              description: "",
              modifier: "rw",
              type: "string",
              default_value: null,
              default_value_set: false,
              validation_type: null,
              validation_parameters: null,
            },
          ],
          embedded_entities: [],
          inter_service_relations: [],
          key_attributes: [],
        },
      ],
      inter_service_relations: [],
      key_attributes: [],
    },
    {
      name: "ext_networkBackend",
      description: "The entity represents network backend",
      modifier: "rw+",
      lower_limit: 1,
      upper_limit: 1,
      attributes: [
        {
          name: "type",
          description: "Can be LDP or EVPN",
          modifier: "rw",
          type: "string?",
          default_value: null,
          default_value_set: true,
          validation_type: "enum",
          validation_parameters: {
            names: {
              LDP: "LDP",
              EVPN: "EVPN",
            },
            value: "backend_type",
          },
        },
      ],
      embedded_entities: [],
      inter_service_relations: [],
      key_attributes: [],
    },
  ],
  inter_service_relations: [],
  environment: "8404deea-3621-4bca-9076-6a612115f810",
  name: "carrierEthernetEvc",
  description: null,
  lifecycle: {
    states: [
      {
        name: "update_start",
        label: null,
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_rejected_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "creating",
        label: null,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "rollback",
        label: null,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_rejected",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "rejected",
        label: "danger",
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "acknowledged",
        label: null,
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "terminated",
        label: null,
        export_resources: false,
        validate_self: null,
        validate_others: null,
        purge_resources: false,
        deleted: true,
        values: {},
      },
      {
        name: "start",
        label: null,
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "deleting",
        label: null,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: true,
        deleted: false,
        values: {},
      },
      {
        name: "update_acknowledged_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_acknowledged",
        label: null,
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_failed",
        label: "warning",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "up",
        label: "success",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_start_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_inprogress",
        label: null,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "failed",
        label: "danger",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
    ],
    transfers: [
      {
        source: "start",
        target: "acknowledged",
        error: "rejected",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "initial validation",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "acknowledged",
        target: "creating",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "ack to creating",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "creating",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "creating done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "update_start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to update_start",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start",
        target: "update_acknowledged",
        error: "update_rejected",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "update_start to update_ack",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start_failed",
        target: "update_acknowledged_failed",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "update_start_failed to update_ack_failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_acknowledged",
        target: "update_inprogress",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "update_ack to update_inprogress",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "update_acknowledged_failed",
        target: "update_inprogress",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "update_ack_failed to update_inprogress_failed",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "update_inprogress",
        target: "up",
        error: "update_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start",
        target: "update_start",
        error: "update_start_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update start failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "update_rejected",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "upd_reject failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start_failed",
        target: "update_start",
        error: "update_start_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update start recover",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "update_rejected",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "upd_reject recover",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "up",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "abort update",
        target_operation: "clear candidate",
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "failed",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "abort update failed",
        target_operation: "clear candidate",
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "rollback",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rollback in update_failed",
        target_operation: "rollback",
        error_operation: null,
      },
      {
        source: "rollback",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "rollback done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "failed",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "failed to up",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "up",
        error: "update_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_failed to up",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "rejected",
        target: "start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rejected to start",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "update_start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_rejected to start_update",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "update_start_failed",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_rejected_failed to start_update_failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "creating",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "creating to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_failed to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "failed",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "failed to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "deleting",
        target: "terminated",
        error: "deleting",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "deletion done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "rejected",
        target: "terminated",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rejected to terminated",
        target_operation: null,
        error_operation: null,
      },
    ],
    initial_state: "start",
    name: "lsm::simple",
  },
  config: {},
  service_identity: "identifier",
  service_identity_display_name: "Carrier Ethernet EVC",
  instance_summary: {
    by_state: {
      up: 1,
      update_start: 0,
      update_rejected_failed: 0,
      creating: 0,
      rollback: 0,
      update_rejected: 0,
      rejected: 0,
      acknowledged: 0,
      start: 0,
      deleting: 0,
      update_acknowledged_failed: 0,
      update_acknowledged: 0,
      update_failed: 0,
      update_start_failed: 0,
      update_inprogress: 0,
      failed: 0,
    },
    by_label: {
      no_label: 0,
      info: 0,
      success: 1,
      danger: 0,
      warning: 0,
    },
    total: 1,
  },
  strict_modifier_enforcement: false,
};
