import { ServiceInstanceModel, ServiceModel } from "@/Core";

export const testInstance: ServiceInstanceModel = {
  id: "d938d5bb-8bf1-4b41-9e17-ae0b5069cbbf",
  environment: "ff6dd80a-e18b-4a06-85fc-9a5cf4b45d0b",
  service_entity: "mpn",
  version: 4,
  config: {},
  state: "up",
  candidate_attributes: null,
  active_attributes: {
    mcc: "001",
    mnc: "01",
    name: "bart",
    site: "mpn_site",
    tenant: "mpn",
    peerings: [
      {
        vlan: 20,
        routes: ["10.0.20.128/32,10.0.20.1", "10.0.20.144/32,10.0.20.1"],
        switch: "switch-1",
        peer_asn: 64999,
        port_name: "xe-0/0/7",
        peer_address: "10.0.20.1",
        local_address: "10.0.20.0/31",
      },
    ],
    mgmt_prefix: "172.26.100.0/24",
    tenant_group: "mpn_group",
  },
  rollback_attributes: null,
  created_at: "2023-05-16T07:40:28.868598",
  last_updated: "2023-05-16T07:49:41.067413",
  callback: [],
  deleted: false,
  deployment_progress: {
    total: 335,
    failed: 0,
    deployed: 335,
    waiting: 0,
  },
  service_identity_attribute_value: "bart",
};

export const testService: ServiceModel = {
  attributes: [
    {
      name: "name",
      description: "The name of the mpn to deploy.",
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: null,
      validation_parameters: null,
    },
    {
      name: "mgmt_prefix",
      description:
        "The network to use for the management range. This needs to be at least a /25\nso that two /26 can be created from it.",
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: "ipaddress.IPv4Network",
      validation_parameters: null,
    },
    {
      name: "mcc",
      description: "Mobile country code",
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: null,
      validation_parameters: null,
    },
    {
      name: "mnc",
      description: "Mobile network code",
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: null,
      validation_parameters: null,
    },
    {
      name: "tenant_group",
      description: "desc",
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: null,
      validation_parameters: null,
    },
    {
      name: "tenant",
      description: "desc",
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: null,
      validation_parameters: null,
    },
    {
      name: "site",
      description: "desc",
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: null,
      validation_parameters: null,
    },
  ],
  embedded_entities: [
    {
      name: "peerings",
      description: "desc",
      modifier: "rw+",
      lower_limit: 0,
      upper_limit: undefined,
      attributes: [
        {
          name: "switch",
          description: "The name/id of the switch to do the peering on",
          modifier: "rw",
          type: "string",
          default_value: null,
          default_value_set: false,
          validation_type: "enum",
          validation_parameters: {
            names: {
              "switch-1": "switch-1",
              "switch-2": "switch-2",
              "switch-3": "switch-3",
              "switch-4": "switch-4",
            },
            value: "switch_t",
          },
        },
        {
          name: "port_name",
          description:
            "The name of the port on the switch to create the peering on",
          modifier: "rw",
          type: "string",
          default_value: null,
          default_value_set: false,
          validation_type: null,
          validation_parameters: null,
        },
        {
          name: "local_address",
          description: "The address to set on the interface on the MPN",
          modifier: "rw",
          type: "string",
          default_value: null,
          default_value_set: false,
          validation_type: "ipaddress.IPv4Interface",
          validation_parameters: null,
        },
        {
          name: "peer_address",
          description:
            "The address of the peer. When BPG is used, this is also the peering ip",
          modifier: "rw",
          type: "string?",
          default_value: null,
          default_value_set: true,
          validation_type: "ipaddress.IPv4Address?",
          validation_parameters: null,
        },
        {
          name: "vlan",
          description:
            "The vlan ID to use for this peering. When the vlan is 0 the traffic is untagged. If the vlan is already used\ninternally in the deployment, a validation error will be given.",
          modifier: "rw",
          type: "int",
          default_value: null,
          default_value_set: false,
          validation_type: null,
          validation_parameters: null,
        },
        {
          name: "peer_asn",
          description: "The ASN of the peer to setup the BGP session.",
          modifier: "rw",
          type: "int?",
          default_value: null,
          default_value_set: true,
          validation_type: null,
          validation_parameters: null,
        },
        {
          name: "routes",
          description:
            "Routes are structured as prefix,gateway For example: 0.0.0.0/0,192.0.2.1",
          modifier: "rw",
          type: "string[]",
          default_value: [] as string[],
          default_value_set: true,
          validation_type: "pydantic.constr[]",
          validation_parameters: {
            regex:
              "^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\/\\d{1,2},\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$",
          },
        },
      ],
      embedded_entities: [],
      inter_service_relations: [],
      key_attributes: ["port_name", "switch", "vlan"],
    },
  ],
  inter_service_relations: [],
  environment: "ff6dd80a-e18b-4a06-85fc-9a5cf4b45d0b",
  name: "mpn",
  description:
    "A redundant mobile private network deployment for Core and Transport",
  lifecycle: {
    states: [
      {
        name: "update_inprogress",
        label: null,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_start_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "failed",
        label: "danger",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "rejected",
        label: "danger",
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_failed",
        label: "warning",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_acknowledged",
        label: null,
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "up",
        label: "success",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_rejected",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "rollback",
        label: null,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "start",
        label: null,
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_acknowledged_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "deleting",
        label: null,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: true,
        deleted: false,
        values: {},
      },
      {
        name: "creating",
        label: null,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_rejected_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_start",
        label: null,
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "acknowledged",
        label: null,
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "terminated",
        label: null,
        export_resources: false,
        validate_self: null,
        validate_others: null,
        purge_resources: false,
        deleted: true,
        values: {},
      },
    ],
    transfers: [
      {
        source: "start",
        target: "acknowledged",
        error: "rejected",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "initial validation",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "acknowledged",
        target: "creating",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "ack to creating",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "creating",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "creating done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "update_start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to update_start",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start",
        target: "update_acknowledged",
        error: "update_rejected",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "update_start to update_ack",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start_failed",
        target: "update_acknowledged_failed",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "update_start_failed to update_ack_failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_acknowledged",
        target: "update_inprogress",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "update_ack to update_inprogress",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "update_acknowledged_failed",
        target: "update_inprogress",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "update_ack_failed to update_inprogress_failed",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "update_inprogress",
        target: "up",
        error: "update_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start",
        target: "update_start",
        error: "update_start_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update start failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "update_rejected",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "upd_reject failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start_failed",
        target: "update_start",
        error: "update_start_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update start recover",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "update_rejected",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "upd_reject recover",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "up",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "abort update",
        target_operation: "clear candidate",
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "failed",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "abort update failed",
        target_operation: "clear candidate",
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "rollback",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rollback in update_failed",
        target_operation: "rollback",
        error_operation: null,
      },
      {
        source: "rollback",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "rollback done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "failed",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "failed to up",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "up",
        error: "update_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_failed to up",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "rejected",
        target: "start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rejected to start",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "update_start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_rejected to start_update",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "update_start_failed",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_rejected_failed to start_update_failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "deleting",
        target: "terminated",
        error: "deleting",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "deletion done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "rejected",
        target: "terminated",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rejected to terminated",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "creating",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "creating to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_failed to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "failed",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "failed to deleting",
        target_operation: null,
        error_operation: null,
      },
    ],
    initial_state: "start",
    name: "lsm::simple",
  },
  config: {},
  service_identity: "name",
  service_identity_display_name: "MPN Name",
  instance_summary: {
    by_state: {
      up: 1,
      update_inprogress: 0,
      update_start_failed: 0,
      failed: 0,
      rejected: 0,
      update_failed: 0,
      update_acknowledged: 0,
      update_rejected: 0,
      rollback: 0,
      start: 0,
      update_acknowledged_failed: 0,
      deleting: 0,
      creating: 0,
      update_rejected_failed: 0,
      update_start: 0,
      acknowledged: 0,
    },
    by_label: {
      no_label: 0,
      info: 0,
      success: 1,
      danger: 0,
      warning: 0,
    },
    total: 1,
  },
  strict_modifier_enforcement: true,
};
