export default {
  "compileReports.title": "Compile Reports",
  "compileReports.empty.message": "No compile reports found",
  "compileReports.columns.requested": "Requested",
  "compileReports.columns.message": "Message",
  "compileReports.columns.waitTime": "Wait Time",
  "compileReports.columns.compileTime": "Compile Time",
  "compileReports.columns.actions": "Actions",
  "compileReports.columns.inProgress": "In Progress",
  "compileReports.links.details": "Details",
  "compileReports.filters.status.placeholder": "Select compile status...",
  "compileReports.filters.result.placeholder": "Select result...",
  "compileReports.filters.result.success": "Successful",
  "compileReports.filters.result.failed": "Failed",
};
