export default {
  "compileDetails.title": "Compile Details",
  "compileDetails.status.title": "Status",
  "compileDetails.status.export": "Export",
  "compileDetails.status.update": "Update",
  "compileDetails.status.success": "Success",
  "compileDetails.status.message": "Message",
  "compileDetails.status.trigger": "Trigger",
  "compileDetails.status.envVars": "Environment Variables",
  "compileDetails.errors.title": "Errors",
  "compileDetails.errors.type": "Type",
  "compileDetails.errors.message": "Message",
  "compileDetails.stages.title": "Stages",
  "compileDetails.stages.columns.name": "Name",
  "compileDetails.stages.columns.command": "Command",
  "compileDetails.stages.columns.delay": "Stage start delay",
  "compileDetails.stages.columns.duration": "Duration",
  "compileDetails.stages.columns.returnCode": "Return Code",
  "compileDetails.stages.columns.outstream": "Output Stream",
  "compileDetails.stages.columns.errstream": "Error Stream",
  "compileDetails.stages.copy": "Copy full command to clipboard",
};
