export default {
  "resources.empty.message": "No resources found",
  "resources.column.type": "Type",
  "resources.column.agent": "Agent",
  "resources.column.value": "Value",
  "resources.column.numberOfDependencies": "Number of dependencies",
  "resources.column.deployState": "Deploy State",
  "resources.filters.status.placeholder": "Deploy State...",
  "resources.filters.agent.placeholder": "Agent...",
  "resources.filters.value.placeholder": "Value...",
  "resources.filters.type.placeholder": "Type...",
  "resources.details.title": "Resource Details",
  "resources.info.title": "Info",
  "resources.info.id": "Id",
  "resources.info.lastDeploy": "Last Deploy",
  "resources.info.firstTime": "Created",
  "resources.info.versionLink": "Open resource version details",
  "resources.details.failed.title": "Something went wrong",
  "resources.details.failed.body": (error: string) =>
    `There was an error retrieving data: ${error}`,
  "resources.requires.title": "Requires",
  "resources.requires.empty.message": "No requirements found",
  "resources.requires.failed.title": "Something went wrong",
  "resources.requires.failed.body": (error: string) =>
    `There was an error retrieving data: ${error}`,
  "resources.requires.resourceId": "Resource Id",
  "resources.requires.deployState": "Deploy State",
  "resources.history.title": "History",
  "resources.history.column.numberOfDependencies": "Number of dependencies",
  "resources.history.column.date": "Date",
  "resources.history.tabs.attributes": "Desired State",
  "resources.history.tabs.requires": "Requires",
  "resources.history.empty.message": "No requirements found",
  "resources.history.failed.title": "Something went wrong",
  "resources.history.failed.body": (error: string) =>
    `There was an error retrieving data: ${error}`,
  "resources.attributes.title": "Desired State",
  "resources.logs.title": "Logs",
  "resources.logs.empty.message": "No logs found",
  "resources.logs.failed.title": "Something went wrong",
  "resources.logs.failed.body": (error: string) =>
    `There was an error retrieving data: ${error}`,
  "resources.logs.filterOnAction": (actionType: string) =>
    `Filter on '${actionType}'`,
  "resources.logs.timestamp": "Timestamp",
  "resources.logs.actionType": "Action Type",
  "resources.logs.actionType.placeholder": "Action Type...",
  "resources.logs.logLevel": "Log Level",
  "resources.logs.logLevel.placeholder": "Minimal Log Level...",
  "resources.logs.message": "Message",
  "resources.logs.message.placeholder": "Message...",
  "resources.logs.options": "Options",
};
