description: Resolve issue for Instance Composer form  when is confirmed by pressing enter it will navigate to the home page and interrupt the flow.
issue-nr: 5955
change-type: patch
destination-branches: [iso7]
sections:
  bugfix: "{{description}}"
