import { ServiceModel } from "@/Core";

export const MOCK_MPN: ServiceModel = {
  attributes: [
    {
      name: "name",
      description: "The name of the mpn to deploy.",
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: null,
      validation_parameters: null,
    },
    {
      name: "site",
      description:
        "An inventory reference to the site where to deploy the mpn.",
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: null,
      validation_parameters: null,
    },
    {
      name: "mgmt_prefix",
      description:
        "The network to use for the management range. This needs to be at least a /25\nso that two /26 can be created from it.",
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: undefined,
      validation_parameters: null,
    },
  ],
  embedded_entities: [],
  inter_service_relations: [],
  environment: "ff6dd80a-e18b-4a06-85fc-9a5cf4b45d0b",
  name: "mpn",
  description:
    "A redundant mobile private network deployment for Core and Transport",
  lifecycle: {
    states: [
      {
        name: "failed",
        label: "danger",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_start_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_inprogress",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "creating",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_start",
        label: undefined,
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_rejected_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "rollback",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_rejected",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "rejected",
        label: "danger",
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "acknowledged",
        label: undefined,
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "terminated",
        label: undefined,
        export_resources: false,
        validate_self: null,
        validate_others: null,
        purge_resources: false,
        deleted: true,
        values: {},
      },
      {
        name: "deleting",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: true,
        deleted: false,
        values: {},
      },
      {
        name: "update_acknowledged_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "start",
        label: undefined,
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "up",
        label: "success",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_acknowledged",
        label: undefined,
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_failed",
        label: "warning",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
    ],
    transfers: [
      {
        source: "start",
        target: "acknowledged",
        error: "rejected",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "initial validation",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "acknowledged",
        target: "creating",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "ack to creating",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "creating",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "creating done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "update_start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to update_start",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start",
        target: "update_acknowledged",
        error: "update_rejected",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "update_start to update_ack",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start_failed",
        target: "update_acknowledged_failed",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "update_start_failed to update_ack_failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_acknowledged",
        target: "update_inprogress",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "update_ack to update_inprogress",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "update_acknowledged_failed",
        target: "update_inprogress",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "update_ack_failed to update_inprogress_failed",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "update_inprogress",
        target: "up",
        error: "update_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start",
        target: "update_start",
        error: "update_start_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update start failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "update_rejected",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "upd_reject failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start_failed",
        target: "update_start",
        error: "update_start_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update start recover",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "update_rejected",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "upd_reject recover",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "up",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "abort update",
        target_operation: "clear candidate",
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "failed",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "abort update failed",
        target_operation: "clear candidate",
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "rollback",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rollback in update_failed",
        target_operation: "rollback",
        error_operation: null,
      },
      {
        source: "rollback",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "rollback done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "failed",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "failed to up",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "up",
        error: "update_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_failed to up",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "rejected",
        target: "start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rejected to start",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "update_start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_rejected to start_update",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "update_start_failed",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_rejected_failed to start_update_failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "deleting",
        target: "terminated",
        error: "deleting",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "deletion done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "rejected",
        target: "terminated",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rejected to terminated",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "creating",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "creating to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_failed to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "failed",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "failed to deleting",
        target_operation: null,
        error_operation: null,
      },
    ],
    initial_state: "start",
    name: "lsm::simple",
  },
  config: {},
  service_identity: "name",
  service_identity_display_name: "MPN Name",
  instance_summary: null,
};

export const MOCK_DN: ServiceModel = {
  attributes: [
    {
      name: "name",
      description: undefined,
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: null,
      validation_parameters: null,
    },
    {
      name: "ue_network",
      description: undefined,
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: undefined,
      validation_parameters: null,
    },
  ],
  embedded_entities: [
    {
      name: "peerings",
      description: undefined,
      modifier: "rw+",
      lower_limit: 0,
      upper_limit: 1,
      attributes: [
        {
          name: "local_address",
          description: undefined,
          modifier: "rw",
          type: "string",
          default_value: null,
          default_value_set: false,
          validation_type: "ipaddress.IPv4Address",
          validation_parameters: null,
        },
        {
          name: "peer_address",
          description: undefined,
          modifier: "rw",
          type: "string",
          default_value: null,
          default_value_set: false,
          validation_type: "ipaddress.IPv4Address",
          validation_parameters: null,
        },
        {
          name: "vlan",
          description: undefined,
          modifier: "rw",
          type: "int",
          default_value: null,
          default_value_set: false,
          validation_type: null,
          validation_parameters: null,
        },
        {
          name: "peer_asn",
          description: undefined,
          modifier: "rw",
          type: "int?",
          default_value: null,
          default_value_set: true,
          validation_type: null,
          validation_parameters: null,
        },
        {
          name: "bgp",
          description: undefined,
          modifier: "rw",
          type: "bool",
          default_value: "true",
          default_value_set: true,
          validation_type: null,
          validation_parameters: null,
        },
        {
          name: "routes",
          description: undefined,
          modifier: "rw",
          type: "string[]?",
          default_value: null,
          default_value_set: true,
          validation_type: null,
          validation_parameters: null,
        },
      ],
      embedded_entities: [],
      inter_service_relations: [],
    },
  ],
  inter_service_relations: [
    {
      name: "mpn",
      description:
        "A redundant mobile private network deployment for Core and Transport",
      modifier: "rw",
      lower_limit: 1,
      upper_limit: 1,
      entity_type: "mpn",
    },
  ],
  environment: "ff6dd80a-e18b-4a06-85fc-9a5cf4b45d0b",
  name: "dn",
  description: "A data network on an MPN",
  lifecycle: {
    states: [
      {
        name: "failed",
        label: "danger",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_start_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_inprogress",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "creating",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_start",
        label: undefined,
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_rejected_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "rollback",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_rejected",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "rejected",
        label: "danger",
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "acknowledged",
        label: undefined,
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "terminated",
        label: undefined,
        export_resources: false,
        validate_self: null,
        validate_others: null,
        purge_resources: false,
        deleted: true,
        values: {},
      },
      {
        name: "deleting",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: true,
        deleted: false,
        values: {},
      },
      {
        name: "update_acknowledged_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "start",
        label: undefined,
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "up",
        label: "success",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_acknowledged",
        label: undefined,
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_failed",
        label: "warning",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
    ],
    transfers: [
      {
        source: "start",
        target: "acknowledged",
        error: "rejected",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "initial validation",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "acknowledged",
        target: "creating",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "ack to creating",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "creating",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "creating done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "update_start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to update_start",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start",
        target: "update_acknowledged",
        error: "update_rejected",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "update_start to update_ack",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start_failed",
        target: "update_acknowledged_failed",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "update_start_failed to update_ack_failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_acknowledged",
        target: "update_inprogress",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "update_ack to update_inprogress",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "update_acknowledged_failed",
        target: "update_inprogress",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "update_ack_failed to update_inprogress_failed",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "update_inprogress",
        target: "up",
        error: "update_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start",
        target: "update_start",
        error: "update_start_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update start failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "update_rejected",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "upd_reject failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start_failed",
        target: "update_start",
        error: "update_start_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update start recover",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "update_rejected",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "upd_reject recover",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "up",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "abort update",
        target_operation: "clear candidate",
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "failed",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "abort update failed",
        target_operation: "clear candidate",
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "rollback",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rollback in update_failed",
        target_operation: "rollback",
        error_operation: null,
      },
      {
        source: "rollback",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "rollback done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "failed",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "failed to up",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "up",
        error: "update_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_failed to up",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "rejected",
        target: "start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rejected to start",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "update_start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_rejected to start_update",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "update_start_failed",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_rejected_failed to start_update_failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "deleting",
        target: "terminated",
        error: "deleting",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "deletion done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "rejected",
        target: "terminated",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rejected to terminated",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "creating",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "creating to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_failed to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "failed",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "failed to deleting",
        target_operation: null,
        error_operation: null,
      },
    ],
    initial_state: "start",
    name: "lsm::simple",
  },
  config: {},
  service_identity: "name",
  service_identity_display_name: "DN Name",
  instance_summary: null,
};

export const MOCK_IMS: ServiceModel = {
  attributes: [
    {
      name: "name",
      description: undefined,
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: null,
      validation_parameters: null,
    },
  ],
  embedded_entities: [],
  inter_service_relations: [
    {
      name: "mpn",
      description:
        "A redundant mobile private network deployment for Core and Transport",
      modifier: "rw",
      lower_limit: 1,
      upper_limit: 1,
      entity_type: "mpn",
    },
  ],
  environment: "ff6dd80a-e18b-4a06-85fc-9a5cf4b45d0b",
  name: "ims",
  description: "An IMS deployed on a mobile private network.",
  lifecycle: {
    states: [
      {
        name: "failed",
        label: "danger",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_start_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_inprogress",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "creating",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_start",
        label: undefined,
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_rejected_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "rollback",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_rejected",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "rejected",
        label: "danger",
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "acknowledged",
        label: undefined,
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "terminated",
        label: undefined,
        export_resources: false,
        validate_self: null,
        validate_others: null,
        purge_resources: false,
        deleted: true,
        values: {},
      },
      {
        name: "deleting",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: true,
        deleted: false,
        values: {},
      },
      {
        name: "update_acknowledged_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "start",
        label: undefined,
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "up",
        label: "success",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_acknowledged",
        label: undefined,
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_failed",
        label: "warning",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
    ],
    transfers: [
      {
        source: "start",
        target: "acknowledged",
        error: "rejected",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "initial validation",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "acknowledged",
        target: "creating",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "ack to creating",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "creating",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "creating done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "update_start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to update_start",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start",
        target: "update_acknowledged",
        error: "update_rejected",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "update_start to update_ack",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start_failed",
        target: "update_acknowledged_failed",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "update_start_failed to update_ack_failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_acknowledged",
        target: "update_inprogress",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "update_ack to update_inprogress",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "update_acknowledged_failed",
        target: "update_inprogress",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "update_ack_failed to update_inprogress_failed",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "update_inprogress",
        target: "up",
        error: "update_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start",
        target: "update_start",
        error: "update_start_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update start failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "update_rejected",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "upd_reject failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start_failed",
        target: "update_start",
        error: "update_start_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update start recover",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "update_rejected",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "upd_reject recover",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "up",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "abort update",
        target_operation: "clear candidate",
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "failed",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "abort update failed",
        target_operation: "clear candidate",
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "rollback",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rollback in update_failed",
        target_operation: "rollback",
        error_operation: null,
      },
      {
        source: "rollback",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "rollback done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "failed",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "failed to up",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "up",
        error: "update_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_failed to up",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "rejected",
        target: "start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rejected to start",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "update_start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_rejected to start_update",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "update_start_failed",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_rejected_failed to start_update_failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "deleting",
        target: "terminated",
        error: "deleting",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "deletion done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "rejected",
        target: "terminated",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rejected to terminated",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "creating",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "creating to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_failed to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "failed",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "failed to deleting",
        target_operation: null,
        error_operation: null,
      },
    ],
    initial_state: "start",
    name: "lsm::simple",
  },
  config: {},
  service_identity: "name",
  service_identity_display_name: "IMS Name",
  instance_summary: null,
};

export const MOCK_MCX: ServiceModel = {
  attributes: [
    {
      name: "name",
      description: undefined,
      modifier: "rw",
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: null,
      validation_parameters: null,
    },
  ],
  embedded_entities: [],
  inter_service_relations: [
    {
      name: "mpn",
      description:
        "A redundant mobile private network deployment for Core and Transport",
      modifier: "rw",
      lower_limit: 1,
      upper_limit: 1,
      entity_type: "mpn",
    },
    {
      name: "dn",
      description: "A data network on an MPN",
      modifier: "rw",
      lower_limit: 0,
      upper_limit: undefined,
      entity_type: "dn",
    },
  ],
  environment: "ff6dd80a-e18b-4a06-85fc-9a5cf4b45d0b",
  name: "mcx",
  description: "Mission critical push to talk",
  lifecycle: {
    states: [
      {
        name: "failed",
        label: "danger",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_start_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_inprogress",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "creating",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_start",
        label: undefined,
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_rejected_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "rollback",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_rejected",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "rejected",
        label: "danger",
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "acknowledged",
        label: undefined,
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "terminated",
        label: undefined,
        export_resources: false,
        validate_self: null,
        validate_others: null,
        purge_resources: false,
        deleted: true,
        values: {},
      },
      {
        name: "deleting",
        label: undefined,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: true,
        deleted: false,
        values: {},
      },
      {
        name: "update_acknowledged_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "start",
        label: undefined,
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "up",
        label: "success",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_acknowledged",
        label: undefined,
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_failed",
        label: "warning",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
    ],
    transfers: [
      {
        source: "start",
        target: "acknowledged",
        error: "rejected",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "initial validation",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "acknowledged",
        target: "creating",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "ack to creating",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "creating",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "creating done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "update_start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to update_start",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start",
        target: "update_acknowledged",
        error: "update_rejected",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "update_start to update_ack",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start_failed",
        target: "update_acknowledged_failed",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "update_start_failed to update_ack_failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_acknowledged",
        target: "update_inprogress",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "update_ack to update_inprogress",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "update_acknowledged_failed",
        target: "update_inprogress",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "update_ack_failed to update_inprogress_failed",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "update_inprogress",
        target: "up",
        error: "update_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start",
        target: "update_start",
        error: "update_start_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update start failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "update_rejected",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "upd_reject failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start_failed",
        target: "update_start",
        error: "update_start_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update start recover",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "update_rejected",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "upd_reject recover",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "up",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "abort update",
        target_operation: "clear candidate",
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "failed",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "abort update failed",
        target_operation: "clear candidate",
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "rollback",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rollback in update_failed",
        target_operation: "rollback",
        error_operation: null,
      },
      {
        source: "rollback",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "rollback done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "failed",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "failed to up",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "up",
        error: "update_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_failed to up",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "rejected",
        target: "start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rejected to start",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "update_start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_rejected to start_update",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "update_start_failed",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_rejected_failed to start_update_failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "deleting",
        target: "terminated",
        error: "deleting",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "deletion done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "rejected",
        target: "terminated",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rejected to terminated",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "creating",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "creating to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_failed to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "failed",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "failed to deleting",
        target_operation: null,
        error_operation: null,
      },
    ],
    initial_state: "start",
    name: "lsm::simple",
  },
  config: {},
  service_identity: "name",
  service_identity_display_name: "MCx Name",
  instance_summary: null,
};
