import { EventType, ServiceInstanceModel, ServiceModel } from "@/Core";
import { InstanceLog } from "@/Core/Domain/HistoryLog";

export const instanceData: ServiceInstanceModel = {
  id: "1d96a1ab",
  environment: "5bfe1994-365f-49ec-bff1-fed77bbbf8e6",
  service_entity: "mobileCore",
  service_entity_version: 0,
  version: 4,
  desired_state_version: 4,
  config: {},
  state: "up",
  candidate_attributes: {
    name: "core1",
    site: {
      name: "inmanta-lab-0",
      infra_vendor: "vcenter",
    },
    system_id: 1,
    epc_version: "11.3.2-1",
    telco_ip_range: "192.168.126.0/24",
  },
  active_attributes: {
    name: "core1",
    site: {
      name: "inmanta-lab",
      infra_vendor: "vcenter",
    },
    system_id: 1,
    epc_version: "11.3.2-1",
    telco_ip_range: "192.168.126.0/24",
  },
  rollback_attributes: null,
  created_at: "2022-09-02T11:56:06.852941+00:00",
  last_updated: "2022-09-02T12:01:19.626854+00:00",
  callback: [],
  deleted: false,
  deployment_progress: {
    deployed: 1,
    waiting: 0,
    failed: 0,
    total: 1,
  },
  service_identity_attribute_value: "core1",
  referenced_by: null,
  transfer_context: "stable",
};

export const instanceDataDeleted: ServiceInstanceModel = {
  id: "1d96a1ab",
  environment: "5bfe1994-365f-49ec-bff1-fed77bbbf8e6",
  service_entity: "mobileCore",
  service_entity_version: 0,
  version: 4,
  desired_state_version: 4,
  config: {},
  state: "terminated",
  candidate_attributes: {
    name: "core1",
    site: {
      name: "inmanta-lab-0",
      infra_vendor: "vcenter",
    },
    system_id: 1,
    epc_version: "11.3.2-1",
    telco_ip_range: "192.168.126.0/24",
  },
  active_attributes: {
    name: "core1",
    site: {
      name: "inmanta-lab",
      infra_vendor: "vcenter",
    },
    system_id: 1,
    epc_version: "11.3.2-1",
    telco_ip_range: "192.168.126.0/24",
  },
  rollback_attributes: null,
  created_at: "2022-09-02T11:56:06.852941+00:00",
  last_updated: "2022-09-02T12:01:19.626854+00:00",
  callback: [],
  deleted: true,
  deployment_progress: {
    deployed: 1,
    waiting: 0,
    failed: 0,
    total: 1,
  },
  service_identity_attribute_value: "core1",
  referenced_by: null,
  transfer_context: "stable",
};

export const historyData: InstanceLog[] = [
  {
    service_instance_id: "1d96a1ab",
    environment: "5bfe1994-365f-49ec-bff1-fed77bbbf8e6",
    service_entity: "mobileCore",
    service_entity_version: 0,
    version: 5,
    desired_state_version: 5,
    timestamp: "2022-09-02T12:01:19.626854+00:00",
    config: {},
    state: "up",
    active_attributes: {
      name: "core1",
      site: {
        name: "inmanta-lab",
        infra_vendor: "vcenter",
      },
      system_id: 1,
      epc_version: "11.3.2-1",
      telco_ip_range: "192.168.126.0/24",
    },
    candidate_attributes: {
      name: "core1",
      site: {
        name: "inmanta-lab",
        infra_vendor: "vcenter",
      },
      system_id: 1,
      epc_version: "11.3.2-1",
      telco_ip_range: "192.168.126.0/24",
    },
    rollback_attributes: {
      name: "core1",
      site: {
        name: "inmanta-lab",
        infra_vendor: "vcenter",
      },
      system_id: 1,
      epc_version: "11.3.2-1",
      telco_ip_range: "192.168.126.0/24",
    },
    created_at: "2022-09-02T11:56:06.852941+00:00",
    last_updated: "2022-09-02T12:01:19.626854+00:00",
    callback: [],
    deleted: false,
    events: [
      {
        id: "a60dfb93-18ba-4a47-a368-86703bceda40",
        service_instance_id: "1d96a1ab",
        service_instance_version: 3,
        service_desired_state_version: 3,
        timestamp: "2022-09-02T12:01:19.636409+00:00",
        source: "creating",
        destination: "up",
        message:
          "Service instance 1d96a1ab successfully executed transfer creating -> up (error=False)",
        ignored_transition: false,
        event_correlation_id: "15de0ccc-320c-4f62-ab8a-4d3b05564d00",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.RESOURCE_TRANSITION,
        is_error_transition: false,
      },
      {
        id: "031efd60-575a-43bf-9fa2-6d73bda51bae",
        service_instance_id: "1d96a1ab",
        service_instance_version: 3,
        service_desired_state_version: 3,
        timestamp: "2022-09-02T12:01:19.634064+00:00",
        source: "creating",
        destination: "up",
        message:
          "compile request queued with id 44d81446-0596-4708-80aa-4b7e052d2ab2",
        ignored_transition: false,
        event_correlation_id: "15de0ccc-320c-4f62-ab8a-4d3b05564d00",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: "44d81446-0596-4708-80aa-4b7e052d2ab2",
        event_type: EventType.RESOURCE_TRANSITION,
        is_error_transition: false,
      },
      {
        id: "9e9c4ea6-4ae9-4c51-b9bf-c4b3c3d95170",
        service_instance_id: "1d96a1ab",
        service_instance_version: 3,
        service_desired_state_version: 3,
        timestamp: "2022-09-02T12:01:19.618665+00:00",
        source: "creating",
        destination: "up",
        message:
          "Resource-based transition triggered for service instance 1d96a1ab in environment athonet mpn (5bfe1994-365f-49ec-bff1-fed77bbbf8e6)",
        ignored_transition: false,
        event_correlation_id: "15de0ccc-320c-4f62-ab8a-4d3b05564d00",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.RESOURCE_TRANSITION,
        is_error_transition: false,
      },
    ],
    service_identity_attribute_value: "core1",
    transfer_context: "auto",
  },
  {
    service_instance_id: "1d96a1ab",
    environment: "5bfe1994-365f-49ec-bff1-fed77bbbf8e6",
    service_entity: "mobileCore",
    service_entity_version: 0,
    version: 4,
    desired_state_version: 4,
    timestamp: "2022-09-02T12:01:19.626854+00:00",
    config: {},
    state: "up",
    active_attributes: {
      name: "core1",
      site: {
        name: "inmanta-lab",
        infra_vendor: "vcenter",
      },
      system_id: 1,
      epc_version: "11.3.2-1",
      telco_ip_range: "192.168.126.0/24",
    },
    candidate_attributes: {
      name: "core1",
      site: {
        name: "inmanta-lab",
        infra_vendor: "vcenter",
      },
      system_id: 1,
      epc_version: "11.3.2-1",
      telco_ip_range: "192.168.126.0/24",
    },
    rollback_attributes: null,
    created_at: "2022-09-02T11:56:06.852941+00:00",
    last_updated: "2022-09-02T12:01:19.626854+00:00",
    callback: [],
    deleted: false,
    events: [
      {
        id: "a60dfb93-18ba-4a47-a368-86703bceda40",
        service_instance_id: "1d96a1ab",
        service_instance_version: 3,
        service_desired_state_version: 3,
        timestamp: "2022-09-02T12:01:19.636409+00:00",
        source: "creating",
        destination: "up",
        message:
          "Service instance 1d96a1ab successfully executed transfer creating -> up (error=False)",
        ignored_transition: false,
        event_correlation_id: "15de0ccc-320c-4f62-ab8a-4d3b05564d00",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.RESOURCE_TRANSITION,
        is_error_transition: false,
      },
      {
        id: "031efd60-575a-43bf-9fa2-6d73bda51bae",
        service_instance_id: "1d96a1ab",
        service_instance_version: 3,
        service_desired_state_version: 3,
        timestamp: "2022-09-02T12:01:19.634064+00:00",
        source: "creating",
        destination: "up",
        message:
          "compile request queued with id 44d81446-0596-4708-80aa-4b7e052d2ab2",
        ignored_transition: false,
        event_correlation_id: "15de0ccc-320c-4f62-ab8a-4d3b05564d00",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: "44d81446-0596-4708-80aa-4b7e052d2ab2",
        event_type: EventType.RESOURCE_TRANSITION,
        is_error_transition: false,
      },
      {
        id: "9e9c4ea6-4ae9-4c51-b9bf-c4b3c3d95170",
        service_instance_id: "1d96a1ab",
        service_instance_version: 3,
        service_desired_state_version: 3,
        timestamp: "2022-09-02T12:01:19.618665+00:00",
        source: "creating",
        destination: "up",
        message:
          "Resource-based transition triggered for service instance 1d96a1ab in environment athonet mpn (5bfe1994-365f-49ec-bff1-fed77bbbf8e6)",
        ignored_transition: false,
        event_correlation_id: "15de0ccc-320c-4f62-ab8a-4d3b05564d00",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.RESOURCE_TRANSITION,
        is_error_transition: false,
      },
    ],
    service_identity_attribute_value: "core1",
    transfer_context: "auto",
  },
  {
    service_instance_id: "1d96a1ab",
    environment: "5bfe1994-365f-49ec-bff1-fed77bbbf8e6",
    service_entity: "mobileCore",
    service_entity_version: 0,
    version: 3,
    desired_state_version: 3,
    timestamp: "2022-09-02T11:56:16.118358+00:00",
    config: {},
    state: "creating",
    candidate_attributes: null,
    active_attributes: {
      name: "core1",
      site: {
        name: "inmanta-lab",
        infra_vendor: "vcenter",
      },
      system_id: 1,
      epc_version: "11.3.2-1",
      telco_ip_range: "192.168.126.0/24",
    },
    rollback_attributes: null,
    created_at: "2022-09-02T11:56:06.852941+00:00",
    last_updated: "2022-09-02T11:56:16.118358+00:00",
    callback: [],
    deleted: false,
    events: [
      {
        id: "9008c9eb-960f-40a5-bf14-7298232a7d0e",
        service_instance_id: "1d96a1ab",
        service_instance_version: 2,
        service_desired_state_version: 2,
        timestamp: "2022-09-02T11:56:16.126422+00:00",
        source: "acknowledged",
        destination: "creating",
        message:
          "Service instance 1d96a1ab successfully executed transfer acknowledged -> creating (error=False)",
        ignored_transition: false,
        event_correlation_id: "332bc22f-ff3b-4035-9a95-142cdccb1a66",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.AUTO_TRANSITION,
        is_error_transition: false,
      },
      {
        id: "20eeb71b-fa75-4976-96aa-0ae8f8292978",
        service_instance_id: "1d96a1ab",
        service_instance_version: 2,
        service_desired_state_version: 2,
        timestamp: "2022-09-02T11:56:16.124634+00:00",
        source: "acknowledged",
        destination: "creating",
        message:
          "compile request queued with id d2845b93-8a02-41ca-89cc-6f508be51e2b",
        ignored_transition: false,
        event_correlation_id: "332bc22f-ff3b-4035-9a95-142cdccb1a66",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: "d2845b93-8a02-41ca-89cc-6f508be51e2b",
        event_type: EventType.AUTO_TRANSITION,
        is_error_transition: false,
      },
      {
        id: "d0cc1fe6-e700-4810-9810-8809b6c1635b",
        service_instance_id: "1d96a1ab",
        service_instance_version: 2,
        service_desired_state_version: 2,
        timestamp: "2022-09-02T11:56:16.110061+00:00",
        source: "acknowledged",
        destination: "creating",
        message:
          "Auto transition triggered for service instance 1d96a1ab in environment athonet mpn (5bfe1994-365f-49ec-bff1-fed77bbbf8e6)",
        ignored_transition: false,
        event_correlation_id: "332bc22f-ff3b-4035-9a95-142cdccb1a66",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.AUTO_TRANSITION,
        is_error_transition: false,
      },
    ],
    service_identity_attribute_value: "core1",
    transfer_context: "auto",
  },
  {
    service_instance_id: "1d96a1ab",
    environment: "5bfe1994-365f-49ec-bff1-fed77bbbf8e6",
    service_entity: "mobileCore",
    service_entity_version: 0,
    version: 2,
    desired_state_version: 2,
    timestamp: "2022-09-02T11:56:16.104427+00:00",
    config: {},
    state: "acknowledged",
    candidate_attributes: {
      name: "core1",
      site: {
        name: "inmanta-lab-0",
        infra_vendor: "vcenter",
      },
      system_id: 1,
      epc_version: "11.3.2-1",
      telco_ip_range: "192.168.126.0/24",
    },
    active_attributes: null,
    rollback_attributes: null,
    created_at: "2022-09-02T11:56:06.852941+00:00",
    last_updated: "2022-09-02T11:56:16.104427+00:00",
    callback: [],
    deleted: false,
    events: [
      {
        id: "993a1028-1c64-4105-92f4-8a1807840301",
        service_instance_id: "1d96a1ab",
        service_instance_version: 1,
        service_desired_state_version: 1,
        timestamp: "2022-09-02T11:56:16.106411+00:00",
        source: "start",
        destination: "acknowledged",
        message:
          "Service instance 1d96a1ab successfully executed transfer start -> acknowledged (error=False)",
        ignored_transition: false,
        event_correlation_id: "da9a2f08-cc01-43e1-9363-966ced8bd1c2",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.AUTO_TRANSITION,
        is_error_transition: false,
      },
      {
        id: "7fd9cf18-a4c1-4cc6-8c94-2a4123eb3687",
        service_instance_id: "1d96a1ab",
        service_instance_version: 1,
        service_desired_state_version: 1,
        timestamp: "2022-09-02T11:56:06.869318+00:00",
        source: "start",
        destination: "acknowledged",
        message:
          "Validation compile request queued with id c1d2018b-d1cd-46a8-b59b-7bea82d51008",
        ignored_transition: false,
        event_correlation_id: "da9a2f08-cc01-43e1-9363-966ced8bd1c2",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: "c1d2018b-d1cd-46a8-b59b-7bea82d51008",
        event_type: EventType.AUTO_TRANSITION,
        is_error_transition: false,
      },
      {
        id: "5415ef1b-9fcf-43ba-b778-ccf4b423a39a",
        service_instance_id: "1d96a1ab",
        service_instance_version: 1,
        service_desired_state_version: 1,
        timestamp: "2022-09-02T11:56:06.861492+00:00",
        source: "start",
        destination: "acknowledged",
        message:
          "Auto transition triggered for service instance 1d96a1ab in environment athonet mpn (5bfe1994-365f-49ec-bff1-fed77bbbf8e6)",
        ignored_transition: false,
        event_correlation_id: "da9a2f08-cc01-43e1-9363-966ced8bd1c2",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.AUTO_TRANSITION,
        is_error_transition: false,
      },
    ],
    service_identity_attribute_value: "core1",
    transfer_context: "auto",
  },
  {
    service_instance_id: "1d96a1ab",
    environment: "5bfe1994-365f-49ec-bff1-fed77bbbf8e6",
    service_entity: "mobileCore",
    service_entity_version: 0,
    version: 1,
    desired_state_version: 1,
    timestamp: "2022-09-02T11:56:06.852941+00:00",
    config: {},
    state: "start",
    candidate_attributes: null,
    active_attributes: null,
    rollback_attributes: {
      name: "core1",
      site: {
        name: "inmanta-lab",
        infra_vendor: "vcenter",
      },
      system_id: 1,
      epc_version: "11.3.2-1",
      telco_ip_range: "192.168.126.0/24",
    },
    created_at: "2022-09-02T11:56:06.852941+00:00",
    last_updated: "2022-09-02T11:56:06.852941+00:00",
    callback: [],
    deleted: false,
    events: [
      {
        id: "1299e50d-7bb3-43a1-bf18-2e30df8c5294",
        service_instance_id: "1d96a1ab",
        service_instance_version: 0,
        service_desired_state_version: 0,
        timestamp: "2022-09-02T11:56:06.856231+00:00",
        source: null,
        destination: "start",
        message: "Creation complete",
        ignored_transition: false,
        event_correlation_id: "8713877b-714f-4732-a5db-59e3ad7beac9",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.CREATE_TRANSITION,
        is_error_transition: false,
      },
      {
        id: "cf67338b-0e8b-4371-ab26-438d4cfe3577",
        service_instance_id: "1d96a1ab",
        service_instance_version: 0,
        service_desired_state_version: 0,
        timestamp: "2022-09-02T11:56:06.840534+00:00",
        source: null,
        destination: "start",
        message: "Creation trigger received for service instance 1d96a1ab.",
        ignored_transition: false,
        event_correlation_id: "8713877b-714f-4732-a5db-59e3ad7beac9",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.CREATE_TRANSITION,
        is_error_transition: false,
      },
    ],
    service_identity_attribute_value: "core1",
    transfer_context: "auto",
  },
];
export const logsResponse = {
  data: historyData,
  links: {
    next: "/lsm/v1/service_inventory/Lab/bd1f6d03-a0fc-4ce1-bb42-45de2de33b0b/log?limit=50&sort=version.desc&end=34",
    self: "/lsm/v1/service_inventory/Lab/bd1f6d03-a0fc-4ce1-bb42-45de2de33b0b/log?limit=50&sort=version.desc",
  },
  metadata: {
    total: 83,
    before: 0,
    after: 33,
    page_size: 50,
  },
};
export const serviceModel: ServiceModel = {
  attributes: [
    {
      name: "name",
      description:
        "The name of the mobile core.  It will be used to name\nthe epc virtual machine and some network configuration.",
      modifier: "rw",
      attribute_annotations: {},
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: null,
      validation_parameters: null,
    },
    {
      name: "epc_version",
      description:
        "The version of the epc that should be deployed\nfor this mobile core.",
      modifier: "rw+",
      attribute_annotations: {},
      type: "string",
      default_value: "11.3.2-1",
      default_value_set: true,
      validation_type: "enum",
      validation_parameters: {
        names: {
          "11.3.2-1": "11.3.2-1",
          "11.3.3-1": "11.3.3-1",
        },
        value: "epc_version_t",
      },
    },
    {
      name: "telco_ip_range",
      description:
        "The network in which all rans should connect.\nThe epc will get the first ip in the range for its interface.",
      modifier: "rw",
      attribute_annotations: {},
      type: "string",
      default_value: null,
      default_value_set: false,
      validation_type: "ipaddress.IPv4Network",
      validation_parameters: null,
    },
    {
      name: "system_id",
      description:
        "This value is automatically allocated, based on\nwhat is currently available.  This is used for the licensing\nof the epc we create.",
      modifier: "r",
      attribute_annotations: {},
      type: "int?",
      default_value: null,
      default_value_set: true,
      validation_type: null,
      validation_parameters: null,
    },
  ],
  embedded_entities: [
    {
      name: "site",
      description:
        "The site at which the epc should be deployed.  The name should\n\nmatch a site provided in the config file.",
      modifier: "rw",
      attribute_annotations: {},
      lower_limit: 1,
      upper_limit: 1,
      attributes: [
        {
          name: "infra_vendor",
          description: "The type of vendor at this site.",
          modifier: "rw",
          attribute_annotations: {},
          type: "string",
          default_value: null,
          default_value_set: false,
          validation_type: "enum",
          validation_parameters: {
            names: {
              aws: "aws",
              esxi: "esxi",
              vcenter: "vcenter",
            },
            value: "site_t",
          },
        },
        {
          name: "name",
          description:
            "The name of the site where the mobile core should be deployed.",
          modifier: "rw",
          attribute_annotations: {},
          type: "string",
          default_value: null,
          default_value_set: false,
          validation_type: null,
          validation_parameters: null,
        },
      ],
      embedded_entities: [],
      inter_service_relations: [],
      key_attributes: [],
    },
  ],
  inter_service_relations: [],
  environment: "5bfe1994-365f-49ec-bff1-fed77bbbf8e6",
  name: "mobileCore",
  version: 0,
  description: "Deploy an EPC instance on the specified cluster.",
  lifecycle: {
    states: [
      {
        name: "rejected",
        label: "danger",
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "deleting",
        label: null,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: true,
        deleted: false,
        values: {},
      },
      {
        name: "update_cleanup_failed",
        label: "warning",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_start_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_rejected",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "terminated",
        label: null,
        export_resources: false,
        validate_self: null,
        validate_others: null,
        purge_resources: false,
        deleted: true,
        values: {},
      },
      {
        name: "update_acknowledged",
        label: null,
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_rejected_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "creating",
        label: null,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "start",
        label: null,
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_acknowledged_failed",
        label: "warning",
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_inprogress",
        label: null,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "failed",
        label: "danger",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "rollback",
        label: null,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "acknowledged",
        label: null,
        export_resources: false,
        validate_self: "candidate",
        validate_others: null,
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_failed",
        label: "warning",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "up",
        label: "success",
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_start",
        label: null,
        export_resources: true,
        validate_self: "candidate",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
      {
        name: "update_cleanup",
        label: null,
        export_resources: true,
        validate_self: "active",
        validate_others: "active",
        purge_resources: false,
        deleted: false,
        values: {},
      },
    ],
    transfers: [
      {
        source: "start",
        target: "acknowledged",
        error: "rejected",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "initial validation",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "acknowledged",
        target: "creating",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "ack to creating",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "creating",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "creating done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "update_start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to update_start",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start",
        target: "update_acknowledged",
        error: "update_rejected",
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "update_start to update_ack",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start",
        target: "update_acknowledged_failed",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: true,
        validate: true,
        config_name: null,
        description: "update_start_failed to update_ack_failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_acknowledged",
        target: "update_inprogress",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "update_ack to update_inprogress",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "update_acknowledged_failed",
        target: "update_inprogress",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: true,
        validate: false,
        config_name: null,
        description: "update_ack_failed to update_inprogress_failed",
        target_operation: "promote",
        error_operation: null,
      },
      {
        source: "update_inprogress",
        target: "update_cleanup",
        error: "update_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_inprogress to update_cleanup",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "update_cleanup",
        error: "update_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_failed to update_cleanup",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_cleanup",
        target: "up",
        error: "update_cleanup_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start",
        target: "update_start",
        error: "update_start_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update start failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "update_rejected",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "upd_reject failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_start_failed",
        target: "update_start",
        error: "update_start_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update start recover",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "update_rejected",
        error: "update_rejected_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "upd_reject recover",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "up",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "abort update",
        target_operation: "clear candidate",
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "failed",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "abort update failed",
        target_operation: "clear candidate",
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "rollback",
        error: null,
        on_update: false,
        on_delete: false,
        api_set_state: true,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rollback in update_failed",
        target_operation: "rollback",
        error_operation: null,
      },
      {
        source: "rollback",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "rollback done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "failed",
        target: "up",
        error: "failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "failed to up",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_cleanup_failed",
        target: "up",
        error: "update_cleanup_failed",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_cleanup_failed to up",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "rejected",
        target: "start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rejected to start",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected",
        target: "update_start",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_rejected to start_update",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_rejected_failed",
        target: "update_start_failed",
        error: null,
        on_update: true,
        on_delete: false,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_rejected_failed to start_update_failed",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "deleting",
        target: "terminated",
        error: "deleting",
        on_update: false,
        on_delete: false,
        api_set_state: false,
        resource_based: true,
        auto: false,
        validate: false,
        config_name: null,
        description: "deletion done",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "rejected",
        target: "terminated",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "rejected to terminated",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "up",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "up to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "creating",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "creating to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "update_failed",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "update_failed to deleting",
        target_operation: null,
        error_operation: null,
      },
      {
        source: "failed",
        target: "deleting",
        error: null,
        on_update: false,
        on_delete: true,
        api_set_state: false,
        resource_based: false,
        auto: false,
        validate: false,
        config_name: null,
        description: "failed to deleting",
        target_operation: null,
        error_operation: null,
      },
    ],
    initial_state: "start",
    name: "mpn::simple",
  },
  config: {},
  service_identity: "name",
  service_identity_display_name: "Mobile Core",
  strict_modifier_enforcement: false,
  owner: null,
  relation_to_owner: null,
  instance_summary: null,
  owned_entities: [],
};

export const serviceModelWithConfig: ServiceModel = {
  ...serviceModel,
  config: { option1: true },
};

export const instanceDataWithConfig: ServiceInstanceModel = {
  ...instanceData,
  config: { option1: true },
};

export const instanceDataWithDocumentation: ServiceInstanceModel = {
  ...instanceData,
  active_attributes: {
    topography: "# Getting started\n\nThis is some markdown\n",
  },
};

export const serviceModelWithDocumentation: ServiceModel = {
  ...serviceModel,
  attributes: [
    {
      name: "topography",
      description: "Topography of this instance",
      modifier: "r",
      attribute_annotations: {
        web_icon: "FaBook",
        web_content_type: "text/markdown",
        web_title: "Topography",
        web_presentation: "documentation",
      },
      type: "string",
      default_value: "# Getting started\n\nThis is some markdown\n",
      default_value_set: true,
      validation_type: null,
      validation_parameters: null,
    },
  ],
};

export const historyDataWithDocumentation: InstanceLog[] = [
  {
    service_instance_id: "1d96a1ab",
    environment: "5bfe1994-365f-49ec-bff1-fed77bbbf8e6",
    service_entity: "mobileCore",
    service_entity_version: 0,
    version: 4,
    desired_state_version: 4,
    timestamp: "2022-09-02T12:01:19.626854+00:00",
    config: {},
    state: "up",
    candidate_attributes: null,
    active_attributes: {
      topography: "# We are adding documentation",
    },
    rollback_attributes: null,
    created_at: "2022-09-02T11:56:06.852941+00:00",
    last_updated: "2022-09-02T12:01:19.626854+00:00",
    callback: [],
    deleted: false,
    events: [
      {
        id: "a60dfb93-18ba-4a47-a368-86703bceda40",
        service_instance_id: "1d96a1ab",
        service_instance_version: 3,
        service_desired_state_version: 3,
        timestamp: "2022-09-02T12:01:19.636409+00:00",
        source: "creating",
        destination: "up",
        message:
          "Service instance 1d96a1ab successfully executed transfer creating -> up (error=False)",
        ignored_transition: false,
        event_correlation_id: "15de0ccc-320c-4f62-ab8a-4d3b05564d00",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.RESOURCE_TRANSITION,
        is_error_transition: false,
      },
      {
        id: "031efd60-575a-43bf-9fa2-6d73bda51bae",
        service_instance_id: "1d96a1ab",
        service_instance_version: 3,
        service_desired_state_version: 3,
        timestamp: "2022-09-02T12:01:19.634064+00:00",
        source: "creating",
        destination: "up",
        message:
          "compile request queued with id 44d81446-0596-4708-80aa-4b7e052d2ab2",
        ignored_transition: false,
        event_correlation_id: "15de0ccc-320c-4f62-ab8a-4d3b05564d00",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: "44d81446-0596-4708-80aa-4b7e052d2ab2",
        event_type: EventType.RESOURCE_TRANSITION,
        is_error_transition: false,
      },
      {
        id: "9e9c4ea6-4ae9-4c51-b9bf-c4b3c3d95170",
        service_instance_id: "1d96a1ab",
        service_instance_version: 3,
        service_desired_state_version: 3,
        timestamp: "2022-09-02T12:01:19.618665+00:00",
        source: "creating",
        destination: "up",
        message:
          "Resource-based transition triggered for service instance 1d96a1ab in environment athonet mpn (5bfe1994-365f-49ec-bff1-fed77bbbf8e6)",
        ignored_transition: false,
        event_correlation_id: "15de0ccc-320c-4f62-ab8a-4d3b05564d00",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.RESOURCE_TRANSITION,
        is_error_transition: false,
      },
    ],
    service_identity_attribute_value: "core1",
    transfer_context: "auto",
  },
  {
    service_instance_id: "1d96a1ab",
    environment: "5bfe1994-365f-49ec-bff1-fed77bbbf8e6",
    service_entity: "mobileCore",
    service_entity_version: 0,
    version: 3,
    desired_state_version: 3,
    timestamp: "2022-09-02T11:56:16.118358+00:00",
    config: {},
    state: "creating",
    candidate_attributes: {
      topography: "# We are adding documentation",
    },
    active_attributes: null,
    rollback_attributes: null,
    created_at: "2022-09-02T11:56:06.852941+00:00",
    last_updated: "2022-09-02T11:56:16.118358+00:00",
    callback: [],
    deleted: false,
    events: [
      {
        id: "9008c9eb-960f-40a5-bf14-7298232a7d0e",
        service_instance_id: "1d96a1ab",
        service_instance_version: 2,
        service_desired_state_version: 2,
        timestamp: "2022-09-02T11:56:16.126422+00:00",
        source: "acknowledged",
        destination: "creating",
        message:
          "Service instance 1d96a1ab successfully executed transfer with validation report acknowledged -> creating (error=False)",
        ignored_transition: false,
        event_correlation_id: "332bc22f-ff3b-4035-9a95-142cdccb1a66",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: "xxx-report-id",
        event_type: EventType.AUTO_TRANSITION,
        is_error_transition: false,
      },
      {
        id: "20eeb71b-fa75-4976-96aa-0ae8f8292978",
        service_instance_id: "1d96a1ab",
        service_instance_version: 2,
        service_desired_state_version: 2,
        timestamp: "2022-09-02T11:56:16.124634+00:00",
        source: "acknowledged",
        destination: "creating",
        message:
          "compile request queued with id d2845b93-8a02-41ca-89cc-6f508be51e2b",
        ignored_transition: false,
        event_correlation_id: "332bc22f-ff3b-4035-9a95-142cdccb1a66",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: "d2845b93-8a02-41ca-89cc-6f508be51e2b",
        event_type: EventType.AUTO_TRANSITION,
        is_error_transition: true,
      },
      {
        id: "d0cc1fe6-e700-4810-9810-8809b6c1635b",
        service_instance_id: "1d96a1ab",
        service_instance_version: 2,
        service_desired_state_version: 2,
        timestamp: "2022-09-02T11:56:16.110061+00:00",
        source: "acknowledged",
        destination: "creating",
        message:
          "Auto transition triggered for service instance 1d96a1ab in environment athonet mpn (5bfe1994-365f-49ec-bff1-fed77bbbf8e6)",
        ignored_transition: false,
        event_correlation_id: "332bc22f-ff3b-4035-9a95-142cdccb1a66",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.AUTO_TRANSITION,
        is_error_transition: false,
      },
    ],
    service_identity_attribute_value: "core1",
    transfer_context: "auto",
  },
  {
    service_instance_id: "1d96a1ab",
    environment: "5bfe1994-365f-49ec-bff1-fed77bbbf8e6",
    service_entity: "mobileCore",
    service_entity_version: 0,
    version: 2,
    desired_state_version: 2,
    timestamp: "2022-09-02T11:56:16.104427+00:00",
    config: {},
    state: "acknowledged",
    candidate_attributes: null,
    active_attributes: null,
    rollback_attributes: {
      topography: "",
    },
    created_at: "2022-09-02T11:56:06.852941+00:00",
    last_updated: "2022-09-02T11:56:16.104427+00:00",
    callback: [],
    deleted: false,
    events: [
      {
        id: "993a1028-1c64-4105-92f4-8a1807840301",
        service_instance_id: "1d96a1ab",
        service_instance_version: 1,
        service_desired_state_version: 1,
        timestamp: "2022-09-02T11:56:16.106411+00:00",
        source: "start",
        destination: "acknowledged",
        message:
          "Service instance 1d96a1ab successfully executed transfer start -> acknowledged (error=False)",
        ignored_transition: false,
        event_correlation_id: "da9a2f08-cc01-43e1-9363-966ced8bd1c2",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.AUTO_TRANSITION,
        is_error_transition: false,
      },
      {
        id: "7fd9cf18-a4c1-4cc6-8c94-2a4123eb3687",
        service_instance_id: "1d96a1ab",
        service_instance_version: 1,
        service_desired_state_version: 1,
        timestamp: "2022-09-02T11:56:06.869318+00:00",
        source: "start",
        destination: "acknowledged",
        message:
          "Validation compile request queued with id c1d2018b-d1cd-46a8-b59b-7bea82d51008",
        ignored_transition: false,
        event_correlation_id: "da9a2f08-cc01-43e1-9363-966ced8bd1c2",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: "c1d2018b-d1cd-46a8-b59b-7bea82d51008",
        event_type: EventType.AUTO_TRANSITION,
        is_error_transition: false,
      },
      {
        id: "5415ef1b-9fcf-43ba-b778-ccf4b423a39a",
        service_instance_id: "1d96a1ab",
        service_instance_version: 1,
        service_desired_state_version: 1,
        timestamp: "2022-09-02T11:56:06.861492+00:00",
        source: "start",
        destination: "acknowledged",
        message:
          "Auto transition triggered for service instance 1d96a1ab in environment athonet mpn (5bfe1994-365f-49ec-bff1-fed77bbbf8e6)",
        ignored_transition: false,
        event_correlation_id: "da9a2f08-cc01-43e1-9363-966ced8bd1c2",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.AUTO_TRANSITION,
        is_error_transition: false,
      },
    ],
    service_identity_attribute_value: "core1",
    transfer_context: "auto",
  },
  {
    service_instance_id: "1d96a1ab",
    environment: "5bfe1994-365f-49ec-bff1-fed77bbbf8e6",
    service_entity: "mobileCore",
    service_entity_version: 0,
    version: 1,
    desired_state_version: 1,
    timestamp: "2022-09-02T11:56:06.852941+00:00",
    config: {},
    state: "start",
    candidate_attributes: {
      name: "old version, no doc back then.",
    },
    active_attributes: null,
    rollback_attributes: null,
    created_at: "2022-09-02T11:56:06.852941+00:00",
    last_updated: "2022-09-02T11:56:06.852941+00:00",
    callback: [],
    deleted: false,
    events: [
      {
        id: "1299e50d-7bb3-43a1-bf18-2e30df8c5294",
        service_instance_id: "1d96a1ab",
        service_instance_version: 0,
        service_desired_state_version: 0,
        timestamp: "2022-09-02T11:56:06.856231+00:00",
        source: null,
        destination: "start",
        message: "Creation complete",
        ignored_transition: false,
        event_correlation_id: "8713877b-714f-4732-a5db-59e3ad7beac9",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.CREATE_TRANSITION,
        is_error_transition: false,
      },
      {
        id: "cf67338b-0e8b-4371-ab26-438d4cfe3577",
        service_instance_id: "1d96a1ab",
        service_instance_version: 0,
        service_desired_state_version: 0,
        timestamp: "2022-09-02T11:56:06.840534+00:00",
        source: null,
        destination: "start",
        message: "Creation trigger received for service instance 1d96a1ab.",
        ignored_transition: false,
        event_correlation_id: "8713877b-714f-4732-a5db-59e3ad7beac9",
        severity: 20,
        severity_text: "INFO",
        id_compile_report: null,
        event_type: EventType.CREATE_TRANSITION,
        is_error_transition: false,
      },
    ],
    service_identity_attribute_value: "core1",
    transfer_context: "auto",
  },
];

export const logsWithDocumentationResponse = {
  data: historyDataWithDocumentation,
  links: {
    next: "/lsm/v1/service_inventory/Lab/bd1f6d03-a0fc-4ce1-bb42-45de2de33b0b/log?limit=50&sort=version.desc&end=34",
    self: "/lsm/v1/service_inventory/Lab/bd1f6d03-a0fc-4ce1-bb42-45de2de33b0b/log?limit=50&sort=version.desc",
  },
  metadata: {
    total: 83,
    before: 0,
    after: 33,
    page_size: 50,
  },
};

export const JSONSchema = {
  data: {
    $defs: {
      clab_host_t: {
        enum: [
          "node1.ii.inmanta.com",
          "node9.ii.inmanta.com",
          "node11.ii.inmanta.com",
          "node12.ii.inmanta.com",
          "node13.ii.inmanta.com",
        ],
        title: "clab_host_t",
        type: "string",
      },
      debug_level_t: {
        enum: ["INFO", "DEBUG", "ERROR", "WARNING"],
        title: "debug_level_t",
        type: "string",
      },
      peerings: {
        additionalProperties: false,
        properties: {
          peer_address: {
            format: "ipv4",
            title: "Peer Address",
            type: "string",
          },
          peer_asn: {
            title: "Peer Asn",
            type: "integer",
          },
          allowed_prefixes: {
            anyOf: [
              {
                items: {
                  format: "ipv4network",
                  type: "string",
                },
                type: "array",
              },
              {
                type: "null",
              },
            ],
            default: null,
            title: "Allowed Prefixes",
          },
        },
        required: ["peer_address", "peer_asn"],
        title: "peerings",
        type: "object",
      },
    },
    additionalProperties: false,
    properties: {
      name: {
        maxLength: 12,
        minLength: 2,
        title: "Name",
        type: "string",
      },
      lab_index: {
        maximum: 255,
        minimum: 0,
        title: "Lab Index",
        type: "integer",
      },
      lab_topology: {
        title: "Lab Topology",
        type: "string",
      },
      loglevel: {
        allOf: [
          {
            $ref: "#/$defs/debug_level_t",
          },
        ],
        default: "INFO",
      },
      iso_version: {
        default: "dev",
        pattern: "^((\\d+(-dev)?)|dev)$",
        title: "Iso Version",
        type: "string",
      },
      clab_host: {
        $ref: "#/$defs/clab_host_t",
      },
      description: {
        default: "",
        title: "Description",
        type: "string",
      },
      peerings: {
        default: [],
        items: {
          $ref: "#/$defs/peerings",
        },
        title: "Peerings",
        type: "array",
      },
    },
    required: ["name", "lab_index", "lab_topology", "clab_host"],
    title: "containerlab",
    type: "object",
  },
};
