export enum EventType {
  CREATE_TRANSITION = "CREATE_TRANSITION",
  API_SET_STATE_TRANSITION = "API_SET_STATE_TRANSITION",
  ON_UPDATE_TRANSITION = "ON_UPDATE_TRANSITION",
  ON_DELETE_TRANSITION = "ON_DELETE_TRANSITION",
  RESOURCE_TRANSITION = "RESOURCE_TRANSITION",
  RESOURCE_EVENT = "RESOURCE_EVENT",
  AUTO_TRANSITION = "AUTO_TRANSITION",
  ALLOCATION_UPDATE = "ALLOCATION_UPDATE",
  FORCE_UPDATE = "FORCE_UPDATE",
  FORCE_DELETE = "FORCE_DELETE",
}

export const EventTypesList = Object.values(EventType).sort();
