import {
  chart_color_black_200,
  chart_color_black_400,
  chart_color_blue_300,
  chart_color_blue_500,
  chart_color_green_200,
  chart_theme_gray_ColorScale_300,
  chart_global_danger_Color_100,
  chart_global_warning_Color_100,
  chart_color_purple_300,
} from "@patternfly/react-tokens";

export const colorTheme = {
  default: chart_color_green_200.var,
  down: chart_global_danger_Color_100.var,
  paused: chart_global_warning_Color_100.var,
  up: chart_color_green_200.var,
  deploying: chart_global_warning_Color_100.var,
  dry: chart_color_black_200.var,
  unavailable: chart_color_black_400.var,
  deployed: chart_color_green_200.var,
  undefined: chart_color_purple_300.var,
  available: chart_color_green_200.var,
  skipped_for_undefined: chart_color_blue_300.var,
  skipped: chart_color_blue_500.var,
  failed: chart_global_danger_Color_100.var,
  cancelled: chart_global_danger_Color_100.var,
  danger: chart_global_danger_Color_100.var,
  info: chart_color_blue_300.var,
  warning: chart_global_warning_Color_100.var,
  no_label: chart_theme_gray_ColorScale_300.var,
};
