description: "Propagate suggestions to embedded entities and allow 0 as valid default input"
issue-nr: 5717
change-type: patch
destination-branches: [master, iso7]
sections:
  minor-improvement: "{{description}}"
